try-badger tables
FlipsideCrypto/polygon-models pull request #137
Opened 2023-04-08 00:06 UTC by antonyip

2023-04-08 02:12 UTC, austinFlipside requested changes

2023-04-08 02:16 UTC, austinFlipside commented
please also add dbt tests to silver

2023-04-08 03:50 UTC, antonyip commented on models/gold/try_badger/core__ez_try_badger_badge_details.sql
Hi @austinFlipside, don't really understand this statement.

The files are inside the `models/gold/try_badger` folder
![image](https://user-images.githubusercontent.com/9086733/230701940-fdc01707-17a3-4457-8ecb-896e18a5c7f7.png)

2023-04-08 03:51 UTC, antonyip commented
Hi @austinFlipside, made the review changes. let me know if you find more issues :)

2023-04-08 04:38 UTC, austinFlipside requested changes

2023-04-08 04:38 UTC, austinFlipside commented on models/gold/try_badger/core__ez_try_badger_badge_details.sql
The folders are good, but the files are named `core__`, so they will be built in the core schema. Please change `core__` to `badger__` in the file names and correspond `.ymls` to change the schema name.

2023-04-08 05:06 UTC, drakedanner commented
@austinFlipside what's best practice on using something like origin_function_signature vs. pulling the first set of chars from the input on traces?

It's been awhile since I've worked with Flipside's Bronze/Silver/Gold layer, so I am not familiar with what's available at each scope and/or the preferred way to build out community curated models.

I _wish_ we had ABIs to drive decoded logs for these, because I suspect we could support custom curated models built off of the decoded logs? 

V2 is coming and will have decoded ABIs on Polygonscan which I'll submit for decoding. In the meantime I am very eager to make V1 analysis more accessible -- thank you @antonyip for moving this forward. Looking forward to QAing these with you live and working on changes 

Another point --- v2 of Badger is quite different. It would be cool to handle v1 and v2 in a cohesive way if possible. Unfortunately, tough for me to speak well to that until we're fully deployed and have data volume to compare.

2023-04-11 12:59 UTC, austinFlipside commented
@antonyip I think @drakedanner makes good points about v1 vs. v2. We do not want to have to deprecate / change the tables when v2 launches. I am cool with the schema being either `badger_v1` or `try_badger_v1`, up to you two. I don't think we can do it as a column without knowing the v2 structure.

2023-04-11 22:27 UTC, antonyip commented
> @antonyip I think @drakedanner makes good points about v1 vs. v2. We do not want to have to deprecate / change the tables when v2 launches. I am cool with the schema being either `badger_v1` or `try_badger_v1`, up to you two. I don't think we can do it as a column without knowing the v2 structure.

done.

2025-05-16 01:37 UTC, closed without merging